CREATE TABLE cotacao (
id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
moeda VARCHAR(25) NOT NULL,
valor_cotacao DOUBLE NOT NULL
) ENGINE = 	InnoDB;

INSERT INTO cotacao VALUES
(DEFAULT,'Dolar', 2.94),
(DEFAULT,'Euro',3.96);
